/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdvertisementCard: typeof import('./src/components/widgets/AdvertisementCard/AdvertisementCard.vue')['default']
    BaseDialog: typeof import('./src/components/common/BaseDialog/BaseDialog.vue')['default']
    CInput: typeof import('./src/components/common/CInput/CInput.vue')['default']
    CreateAdvertisementForm: typeof import('./src/components/Forms/CreateAdvertisementForm.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GoogleAuth: typeof import('./src/components/widgets/GoogleAuth.vue')['default']
    GoogleRegistrationForm: typeof import('./src/components/Forms/GoogleRegistrationForm.vue')['default']
    IconTemplate: typeof import('./src/components/common/IconTemplate.vue')['default']
    ImagesUpload: typeof import('./src/components/widgets/buttons/ImagesUpload.vue')['default']
    NewAdvertisement: typeof import('./src/components/widgets/buttons/NewAdvertisement.vue')['default']
    ProfileIcon: typeof import('./src/components/widgets/buttons/ProfileIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/widgets/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/widgets/TheHeader.vue')['default']
    TheNotification: typeof import('./src/components/widgets/buttons/TheNotification.vue')['default']
  }
}
