# Generated by Django 4.1.6 on 2023-04-24 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisement', '0002_alter_advertisementcategory_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Открыта'), ('SUCCESSFULLY_COMPLETED', 'Успешно завершена'), ('CANCELLED', 'Отменена')], max_length=22, verbose_name='Статус объявления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('is_response', models.BooleanField(default=False)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='advertisement.advertisement', verbose_name='Объявление')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_deals', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_deals', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
        ),
    ]
