# Generated by Django 4.1.6 on 2023-04-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementcategory',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
