# Generated by Django 4.1.6 on 2023-03-10 08:33

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('EXCHANGE', 'Обмен'), ('SELL', 'Продам'), ('BUY', 'Куплю'), ('GIVE', 'Отдам'), ('TAKE', 'Возьму')], max_length=100),
        ),
    ]
