# Generated by Django 4.1.6 on 2023-04-07 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='urgency',
            new_name='urgency_type',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='advertisement.advertisement'),
        ),
    ]
