# Generated by Django 4.1.6 on 2023-06-04 18:07

import colorfield.fields
import imagekit.models.fields
from django.db import migrations, models

import apps.user.models
import utils.colors


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[apps.user.models.validate_email_address], verbose_name='Почта')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия')),
                ('room_number', models.PositiveIntegerField(null=True, verbose_name='Номер комнаты')),
                ('avatar', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='', verbose_name='Аватарка пользователя')),
                ('avatar_color', colorfield.fields.ColorField(blank=True, default=utils.colors.generate_random_color, image_field=None, max_length=18, null=True, samples=None, verbose_name='Цвет аватарки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен ли пользователь?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Пользователь является администратором?')),
                ('is_register', models.BooleanField(default=False, verbose_name='Пользователь зарегистрирован?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
