# Generated by Django 4.1.6 on 2023-05-01 17:05

import colorfield.fields
from django.db import migrations, models

import utils.colors


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_color',
            field=colorfield.fields.ColorField(blank=True, default=utils.colors.generate_random_color, image_field=None, max_length=18, null=True, samples=None, verbose_name='Цвет аватарки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен ли пользователь?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_register',
            field=models.BooleanField(default=False, verbose_name='Пользователь зарегистрирован?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Пользователь является администратором?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
