# Generated by Django 4.1.6 on 2023-03-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='room_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Номер комнаты'),
        ),
    ]
