# Generated by Django 4.1.6 on 2023-03-10 07:36

from django.db import migrations, models

import apps.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[apps.user.models.validate_email_address], verbose_name='Почта'),
        ),
    ]
