# Generated by Django 4.1.6 on 2023-03-10 07:50

from django.db import migrations, models

import apps.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, validators=[apps.user.models.validate_email_address], verbose_name='Почта'),
        ),
    ]
